import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, PackageCheck, RefreshCw, Search, Truck } from "lucide-react";
import { Helmet } from "react-helmet-async";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import shipmentService from "../services/shipment.service";
import type { Shipment, ShipmentStatus } from "../types/logistics.types";

const labels: Record<ShipmentStatus,string> = { pending:"Pending", "label-created":"Label created", "picked-up":"Picked up", "in-transit":"In transit", "out-for-delivery":"Out for delivery", delivered:"Delivered", "failed-delivery":"Failed delivery", returned:"Returned", cancelled:"Cancelled" };
const next: Partial<Record<ShipmentStatus,ShipmentStatus>> = { pending:"label-created", "label-created":"picked-up", "picked-up":"in-transit", "in-transit":"out-for-delivery", "out-for-delivery":"delivered", "failed-delivery":"out-for-delivery" };

export default function LogisticsOperationsPage() {
  const [version,setVersion]=useState(0); const [query,setQuery]=useState("");
  const shipments=useMemo(()=>shipmentService.list(),[version]); const summary=useMemo(()=>shipmentService.summary(),[version]);
  const visible=shipments.filter(s=>`${s.trackingNumber} ${s.orderNumber} ${s.carrierName} ${s.destination.city}`.toLowerCase().includes(query.toLowerCase()));
  const advance=(shipment:Shipment)=>{ const status=next[shipment.status]; if(status){ shipmentService.updateStatus(shipment.id,status); setVersion(v=>v+1); } };
  return <><Helmet><title>Logistics Operations | BredaBuy Admin</title></Helmet><main className="container mx-auto space-y-8 px-4 py-8"><header><p className="text-sm font-medium text-primary">Operations</p><h1 className="text-3xl font-bold">Logistics control centre</h1><p className="mt-2 text-muted-foreground">Monitor shipments, delivery exceptions and carrier activity.</p></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{[["Total",summary.total,Truck],["Pending",summary.pending,PackageCheck],["In transit",summary.inTransit,Truck],["Out for delivery",summary.outForDelivery,Truck],["Delivered",summary.delivered,CheckCircle2],["Exceptions",summary.failedDelivery+summary.returned,AlertTriangle]].map(([name,value,Icon])=><Card key={name as string}><CardContent className="pt-6"><Icon className="mb-3 h-5 w-5 text-muted-foreground"/><p className="text-2xl font-bold">{value as number}</p><p className="text-xs text-muted-foreground">{name as string}</p></CardContent></Card>)}</section><Card><CardHeader><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><CardTitle>Shipments</CardTitle><div className="relative w-full md:w-80"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tracking, order, carrier, city" aria-label="Search shipments"/></div></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Tracking</th><th className="p-3">Order</th><th className="p-3">Destination</th><th className="p-3">Carrier</th><th className="p-3">Status</th><th className="p-3 text-right">Action</th></tr></thead><tbody>{visible.map(s=><tr key={s.id} className="border-b last:border-0"><td className="p-3 font-medium">{s.trackingNumber}</td><td className="p-3">{s.orderNumber}</td><td className="p-3">{s.destination.city}, {s.destination.region}</td><td className="p-3">{s.carrierName}</td><td className="p-3"><Badge variant={s.status==="failed-delivery"||s.status==="returned"?"destructive":s.status==="delivered"?"secondary":"default"}>{labels[s.status]}</Badge></td><td className="p-3 text-right">{next[s.status]&&<Button size="sm" variant="outline" onClick={()=>advance(s)}><RefreshCw className="mr-2 h-3.5 w-3.5"/>{next[s.status]==="delivered"?"Confirm delivery":"Advance"}</Button>}</td></tr>)}{visible.length===0&&<tr><td colSpan={6} className="p-8 text-center text-muted-foreground">No shipments found.</td></tr>}</tbody></table></div></CardContent></Card></main></>;
}
