import { FormEvent, useState } from "react";
import { Search, Truck, CheckCircle2, MapPin, Clock3 } from "lucide-react";
import { Helmet } from "react-helmet-async";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import shipmentService from "../services/shipment.service";
import type { ShipmentStatus } from "../types/logistics.types";

const labels: Record<ShipmentStatus,string> = { pending:"Pending", "label-created":"Label created", "picked-up":"Picked up", "in-transit":"In transit", "out-for-delivery":"Out for delivery", delivered:"Delivered", "failed-delivery":"Delivery attempt failed", returned:"Returned", cancelled:"Cancelled" };

export default function TrackShipmentPage() {
  const [value,setValue]=useState(""); const [tracking,setTracking]=useState(""); const [error,setError]=useState("");
  const shipment = tracking ? shipmentService.track(tracking) : null;
  const events = shipment ? shipmentService.events(shipment.id) : [];
  const submit=(event:FormEvent)=>{event.preventDefault(); setError(""); if(!value.trim()){setError("Enter a tracking number.");return;} setTracking(value.trim()); if(!shipmentService.track(value.trim())) setError("We could not find a shipment with that tracking number.");};
  return <><Helmet><title>Track Your Order | BredaBuy</title><meta name="description" content="Track your BredaBuy shipment and delivery progress."/></Helmet><main className="container mx-auto max-w-4xl px-4 py-10"><div className="mx-auto max-w-2xl text-center"><Badge variant="secondary">BredaBuy Logistics</Badge><h1 className="mt-4 text-3xl font-bold md:text-4xl">Track your shipment</h1><p className="mt-3 text-muted-foreground">Enter your BredaBuy tracking number to see the latest delivery updates.</p><form onSubmit={submit} className="mt-7 flex flex-col gap-3 sm:flex-row"><Input value={value} onChange={e=>setValue(e.target.value)} placeholder="e.g. BB-SHP-ABC123" aria-label="Tracking number"/><Button type="submit"><Search className="mr-2 h-4 w-4"/>Track shipment</Button></form>{error&&<p className="mt-3 text-sm text-destructive" role="alert">{error}</p>}</div>{shipment&&<div className="mt-10 space-y-6"><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle className="flex items-center gap-2"><Truck className="h-5 w-5"/>Shipment {shipment.trackingNumber}</CardTitle><Badge>{labels[shipment.status]}</Badge></div></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Carrier</p><p className="font-medium">{shipment.carrierName}</p></div><div><p className="text-xs text-muted-foreground">Destination</p><p className="font-medium">{shipment.destination.city}, {shipment.destination.region}</p></div><div><p className="text-xs text-muted-foreground">Estimated delivery</p><p className="font-medium">{shipment.estimatedDelivery ? new Date(shipment.estimatedDelivery).toLocaleDateString("en-GH") : "To be confirmed"}</p></div></div></CardContent></Card><Card><CardHeader><CardTitle>Delivery timeline</CardTitle></CardHeader><CardContent><div className="space-y-6">{events.map((event,index)=><div key={event.id} className="relative flex gap-4">{index<events.length-1&&<span className="absolute left-[11px] top-7 h-full w-px bg-border"/>}<div className="relative flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-primary text-primary-foreground">{event.type==="delivered"?<CheckCircle2 className="h-4 w-4"/>:event.location?<MapPin className="h-3.5 w-3.5"/>:<Clock3 className="h-3.5 w-3.5"/>}</div><div className="min-w-0"><p className="font-medium">{event.description}</p><p className="text-sm text-muted-foreground">{new Date(event.occurredAt).toLocaleString("en-GH")}{event.location?` · ${event.location}`:""}</p></div></div>)}</div></CardContent></Card></div>}</main></>;
}
