#!/usr/bin/env bash

set -euo pipefail

echo "============================================================"
echo " BREDA BUY GHANA — EXECUTE PHASE 2 NOW"
echo "============================================================"

echo
echo "You are the implementation agent for BredaBuy Ghana."
echo
echo "The Phase 2 pre-flight has already completed successfully."
echo "TypeScript passes."
echo "ESLint passes with warnings only."
echo "Production build passes."
echo
echo "NOW IMPLEMENT PHASE 2."
echo
echo "IMPORTANT:"
echo "Do NOT merely describe the changes."
echo "Do NOT generate another prompt."
echo "Do NOT stop after analysis."
echo "You must inspect and modify the repository."
echo
echo "Read these files first:"
echo
echo "  docs/reconciliation/ARCHITECTURE_AUDIT.md"
echo "  docs/reconciliation/REPOSITORY_STATE.md"
echo
echo "Then implement the Phase 2 reconciliation described by the audit."
echo
echo "============================================================"
echo "IMPLEMENTATION RULES"
echo "============================================================"
echo
echo "1. Preserve working functionality."
echo "2. Do not blindly rewrite the project."
echo "3. Do not create duplicate routers."
echo "4. Do not create duplicate providers."
echo "5. Do not create duplicate services."
echo "6. Do not replace working functionality unnecessarily."
echo "7. Do not introduce unnecessary dependencies."
echo "8. Do not commit."
echo "9. Do not push."
echo
echo "============================================================"
echo "IMPLEMENTATION ORDER"
echo "============================================================"
echo
echo "PHASE 2.1 — APPLICATION SHELL"
echo "Reconcile:"
echo "  src/main.*"
echo "  src/App.*"
echo "  src/app/providers/"
echo "  src/app/router/"
echo "  src/app/layouts/"
echo
echo "Ensure dependency direction:"
echo "  main"
echo "   -> App"
echo "   -> providers"
echo "   -> router"
echo "   -> layouts"
echo "   -> feature pages"
echo "   -> feature hooks"
echo "   -> services/API"
echo
echo "PHASE 2.2 — PROVIDERS"
echo "Repair provider hierarchy using only providers that actually exist."
echo "Ensure hooks are never executed outside their required provider."
echo
echo "PHASE 2.3 — ROUTING"
echo "Establish one canonical router."
echo "Separate:"
echo "  public"
echo "  customer"
echo "  seller"
echo "  logistics"
echo "  admin"
echo
echo "Fix broken imports, duplicate paths, unreachable routes,"
echo "missing guards, missing 404 handling and suitable lazy loading."
echo
echo "PHASE 2.4 — FEATURES"
echo "Reconcile existing business domains:"
echo "  auth"
echo "  account"
echo "  products"
echo "  search"
echo "  cart"
echo "  checkout"
echo "  orders"
echo "  payments"
echo "  wallet"
echo "  sellers"
echo "  logistics"
echo "  notifications"
echo "  admin"
echo
echo "Do not move files merely for cosmetic reasons."
echo
echo "PHASE 2.5 — SERVICES/DATA"
echo "Establish:"
echo "  Page"
echo "    -> Feature Hook"
echo "    -> Feature Service"
echo "    -> API/Data Layer"
echo "    -> Backend/Data Source"
echo
echo "Remove duplicate implementations only after confirming equivalence."
echo
echo "PHASE 2.6 — SEARCH"
echo "Implement one canonical search flow:"
echo "  SearchInput"
echo "    -> debounce"
echo "    -> search hook"
echo "    -> search service"
echo "    -> API/data source"
echo "    -> results"
echo
echo "Fix:"
echo "  search animation"
echo "  search output"
echo "  stale results"
echo "  duplicate requests"
echo "  loading state"
echo "  empty state"
echo "  error state"
echo "  result positioning"
echo "  keyboard interaction"
echo "  mobile behavior"
echo
echo "Do not create a second search system."
echo
echo "PHASE 2.7 — CART/CHECKOUT/ORDERS"
echo "Verify:"
echo "  Product"
echo "    -> Cart"
echo "    -> Checkout"
echo "    -> Payment"
echo "    -> Order"
echo "    -> Shipment"
echo "    -> Delivery"
echo "    -> Order History"
echo
echo "Prevent duplicate checkout submissions."
echo "Maintain one authoritative order state."
echo
echo "PHASE 2.8 — PAYMENTS/WALLET"
echo "All payment operations must use services."
echo "All wallet operations must use wallet services."
echo "Never mutate wallet balances directly from UI components."
echo "Never expose secrets in frontend code."
echo
echo "PHASE 2.9 — MISSING PAGES"
echo "Use the Phase 1 audit."
echo "Implement referenced missing pages only when supported by the existing"
echo "business architecture."
echo
echo "Every implemented page must have:"
echo "  loading state"
echo "  error state"
echo "  empty state where appropriate"
echo "  correct access control"
echo "  correct service dependencies"
echo "  correct navigation"
echo
echo "PHASE 2.10 — UI"
echo "Preserve the existing BredaBuy design system."
echo "Reuse shared UI components."
echo "Do not create duplicate buttons/cards/headers/dialogs."
echo
echo "PHASE 2.11 — PERFORMANCE"
echo "Optimize verified bottlenecks."
echo "Prioritize:"
echo "  route-level lazy loading"
echo "  code splitting"
echo "  duplicate request elimination"
echo "  sensible caching"
echo "  stable query keys"
echo "  unnecessary context updates"
echo "  efficient list rendering"
echo "  image optimization"
echo "  startup work"
echo
echo "Do not add memoization everywhere."
echo
echo "============================================================"
echo "VALIDATION"
echo "============================================================"
echo
echo "After each logical group of changes run:"
echo
echo "  npx tsc --noEmit"
echo "  npm run lint"
echo "  npm run build"
echo
echo "Fix genuine errors before continuing."
echo "Do not suppress errors simply to make validation pass."
echo
echo "============================================================"
echo "FINAL VALIDATION"
echo "============================================================"
echo
echo "Verify:"
echo "  application starts"
echo "  public routes work"
echo "  auth works"
echo "  customer routes work"
echo "  seller routes work"
echo "  admin routes work"
echo "  logistics routes work"
echo "  products work"
echo "  search works"
echo "  cart works"
echo "  checkout works"
echo "  payments remain protected"
echo "  wallet remains service-controlled"
echo "  orders remain consistent"
echo "  no duplicate providers"
echo "  no duplicate routers"
echo "  no duplicate services"
echo "  no broken imports"
echo "  no genuine placeholders"
echo "  no frontend secrets"
echo "  TypeScript passes"
echo "  ESLint passes"
echo "  production build passes"
echo
echo "============================================================"
echo "PHASE 2 REPORT"
echo "============================================================"
echo
echo "Create:"
echo
echo "  docs/reconciliation/PHASE_2_VALIDATION.md"
echo
echo "Include:"
echo "  Architecture Changes"
echo "  Provider Changes"
echo "  Route Changes"
echo "  Feature Changes"
echo "  Service/Data Changes"
echo "  Search Changes"
echo "  Performance Changes"
echo "  UI Changes"
echo "  Security Changes"
echo "  Missing Pages Implemented"
echo "  Remaining Issues"
echo "  Validation Results"
echo "  Files Changed"
echo "  Recommended Phase 3"
echo
echo "============================================================"
echo "STOP"
echo "============================================================"
echo
echo "Do NOT run:"
echo "  git add"
echo "  git commit"
echo "  git push"
echo
echo "PHASE 2 COMPLETE — WAITING FOR DEVELOPER REVIEW."
