import {
  PERMISSIONS,
  type Permission,
} from "./permissions";

export const SYSTEM_ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMINISTRATOR: "administrator",
  CUSTOMER: "customer",
  SELLER: "seller",
  VENDOR: "vendor",
  RIDER: "rider",
  WAREHOUSE_STAFF: "warehouse_staff",
  FINANCE_OFFICER: "finance_officer",
  CUSTOMER_SERVICE: "customer_service",
} as const;

export type SystemRole =
  (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

const ALL_PERMISSIONS = Object.values(
  PERMISSIONS
) as Permission[];

export const ROLE_PERMISSIONS: Record<
  SystemRole,
  readonly Permission[]
> = {
  super_admin: ALL_PERMISSIONS,

  administrator: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.PRODUCTS_APPROVE,

    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.CATEGORIES_CREATE,
    PERMISSIONS.CATEGORIES_UPDATE,
    PERMISSIONS.CATEGORIES_DELETE,

    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.ORDERS_CANCEL,
    PERMISSIONS.ORDERS_REFUND,

    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_UPDATE,

    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,

    PERMISSIONS.WAREHOUSE_READ,
    PERMISSIONS.WAREHOUSE_TRANSFER,

    PERMISSIONS.SELLERS_READ,
    PERMISSIONS.SELLERS_APPROVE,
    PERMISSIONS.SELLERS_SUSPEND,

    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.FINANCE_REFUND,

    PERMISSIONS.LOGISTICS_READ,
    PERMISSIONS.LOGISTICS_ASSIGN,

    PERMISSIONS.MARKETING_READ,
    PERMISSIONS.MARKETING_CREATE,
    PERMISSIONS.MARKETING_UPDATE,
    PERMISSIONS.MARKETING_DELETE,

    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_MANAGE_ROLES,

    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,

    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_UPDATE,

    PERMISSIONS.CMS_READ,
    PERMISSIONS.CMS_CREATE,
    PERMISSIONS.CMS_UPDATE,
    PERMISSIONS.CMS_DELETE,
  ],

  customer: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.CATEGORIES_READ,

    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_CANCEL,

    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_UPDATE,
  ],

  seller: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,

    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,

    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,

    PERMISSIONS.CUSTOMERS_READ,

    PERMISSIONS.REPORTS_READ,
  ],

  vendor: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,

    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,

    PERMISSIONS.ORDERS_READ,
  ],

  rider: [
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.LOGISTICS_READ,
    PERMISSIONS.LOGISTICS_UPDATE,
  ],

  warehouse_staff: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,

    PERMISSIONS.WAREHOUSE_READ,
    PERMISSIONS.WAREHOUSE_RECEIVE,
    PERMISSIONS.WAREHOUSE_PICK,
    PERMISSIONS.WAREHOUSE_PACK,
    PERMISSIONS.WAREHOUSE_TRANSFER,

    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,
  ],

  finance_officer: [
    PERMISSIONS.ORDERS_READ,

    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_CREATE,
    PERMISSIONS.FINANCE_UPDATE,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.FINANCE_REFUND,

    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  customer_service: [
    PERMISSIONS.PRODUCTS_READ,

    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,

    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_UPDATE,

    PERMISSIONS.REPORTS_READ,
  ],
};

export function roleHasPermission(
  role: SystemRole | undefined | null,
  permission: Permission
): boolean {
  if (!role) {
    return false;
  }

  return ROLE_PERMISSIONS[role]?.includes(
    permission
  ) ?? false;
}

export function roleHasAnyPermission(
  role: SystemRole | undefined | null,
  permissions: Permission[]
): boolean {
  return permissions.some((permission) =>
    roleHasPermission(role, permission)
  );
}

export function roleHasAllPermissions(
  role: SystemRole | undefined | null,
  permissions: Permission[]
): boolean {
  return permissions.every((permission) =>
    roleHasPermission(role, permission)
  );
}
